LANG = en_US.UTF-8
SHELL = /bin/bash
.SHELLFLAGS := --norc --noprofile -e -u -o pipefail -c
.DEFAULT_GOAL = all

STATICCHECK = $(GOPATH)/bin/staticcheck

all: check-fmt check-fmt-simplify staticcheck

check-fmt:
	diff -u <(echo -n) <(gofmt -d ./)

check-fmt-simplify:
	diff -u <(echo -n) <(gofmt -s -d ./)

$(STATICCHECK):
	go install honnef.co/go/tools/cmd/staticcheck@latest

staticcheck: $(STATICCHECK)
	staticcheck -go 1.17 ./...
