LANG = en_US.UTF-8
SHELL = /bin/bash
.SHELLFLAGS = -eu -o pipefail -c # run '/bin/bash ... -c /bin/cmd'
.DEFAULT_GOAL = build

STATICCHECK = $(GOPATH)/bin/staticcheck

check-fmt:
	diff -u <(echo -n) <(gofmt -d ./)

check-fmt-simplify:
	diff -u <(echo -n) <(gofmt -s -d ./)

$(STATICCHECK):
	go install honnef.co/go/tools/cmd/staticcheck@latest

staticcheck: $(STATICCHECK)
	staticcheck -go 1.16 ./...
