name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Test, Lint, Vet and Go fmt
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.3
    - name: Lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.31.0
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test ./...
