---
name: Release created
permissions:
  contents: read
on:
  release:
    types:
      - created
jobs:
  released:
    uses: kare/github/.github/workflows/go-release.yaml@main
    with:
      go_module_path: kkn.fi/vanity
      version: ${{ github.event.release.tag_name }}
