---
name: Release created
on:
  release:
    types:
      - created
jobs:
  released:
    uses: kare/github/.github/workflows/go-release.yaml@0.3.4
    inputs:
      go_module_path: kkn.fi/vanity
      version: ${{ github.event.release.tag_name }}
